SMTPFROM: naman.talaycha@myntra.com
SMTPPASS: zpbwaqijzukxwkee
SMTPTO: namanfrost10@gmail.com
SMTPUSER: naman.talaycha@myntra.com
SUBJECT: "testing results"
loc: ~/go/src/github.com/namantalaycha/functional/.git/hooks