#!/bin/bash
touch temp/text.txt
echo "result of Testing:" > temp/text.txt
go test ./middleware >> temp/text.txt
echo "result of Benchmarks :" >> temp/text.txt
go test -bench=. ./middleware >> temp/text.txt
echo "result of Functional Testing:" >> temp/text.txt
go test ./test>> temp/text.txt
echo "result of Functional Benchmarks :" >> temp/text.txt
go test -bench=. ./test >> temp/text.txt

num=`grep "FAIL" -w  temp/text.txt `
echo $num
if [ "$num" !=  "" ]
then
        echo "Test FAIL"
        rm -r temp/text.txt
        exit 1
fi

python3 slackbot.py
 #num = ` temp/text.txt < grep FAIL -m 1| awk '{ print $1}'`
SMTPFROM=naman.talaycha@myntra.com
SMTPTO=namanfrost10@gmail.com
SMTPSERVER=smtp.googlemail.com:587
SMTPUSER=naman.talaycha@myntra.com
SMTPPASS=zpbwaqijzukxwkee
SUBJECT="testing"

sendEmail -f $SMTPFROM -t $SMTPTO -u $SUBJECT -o message-file=temp/text.txt -s $SMTPSERVER -xu $SMTPUSER -xp $SMTPPASS

rm -r temp/text.txt


#` go test ./middleware/ | grep o -m 1| awk '{ print $1}'`
